# Generated by Django 5.0.3 on 2024-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_event_image_path_eventsjoined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset_link_used',
            field=models.BooleanField(default=False),
        ),
    ]
