# Generated by Django 4.2 on 2024-04-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_description'),
        ('myapp', '0007_user_is_reset_link_used'),
    ]

    operations = [
    ]
