# Generated by Django 5.0.3 on 2024-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_merge_20240403_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsjoined',
            name='notify_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
