# Generated by Django 5.0.3 on 2024-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_eventsjoined_notify_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_notify',
            field=models.BooleanField(default=False),
        ),
    ]
